#!/bin/sh

# dev desktop composer.bat file converted to "composer" bash file

## Set PHP_ID if not already set.
if [ -z ${PHP_ID+x} ]; then
  ## echo "var is unset";
  ## If drupal less than 7.5 - then use php 5.6
  ## export PHP_ID="php5_6"
  export PHP_ID="php7_0"
#else
  #echo "var is set to '$PHP_ID'";
fi

export PATH="/c/Program Files (x86)/DevDesktop/$PHP_ID:$PATH"

## set global composer folder to devdesktop
## removed since we admin rights - use deault user profile instead
## export COMPOSER_HOME="/c/Program Files (x86)/DevDesktop/tools"

MY_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

php "$MY_SCRIPT_DIR/composer.phar" ${@}
