#!/bin/sh

# dev desktop composer.bat file converted to "composer" bash file

# Get current directory of this script.
MY_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

## Set PHP_ID if not already set.
if [ -z ${PHP_ID+x} ]; then
  ## echo "var is unset";
  ## If drupal less than 7.5 - then use php 5.6
  ## export PHP_ID="php5_6"

  ## Use latest PHP version we have.
  ## \ runs real ls, no alias, with / appended to folders
  for i in `\ls "$(cd "$MY_SCRIPT_DIR" && cd .. && pwd)" | grep "php[0-9]" | sort -rV`; do
    export PHP_ID="$i"
    break
  done;

#else
  #echo "var is set to '$PHP_ID'";
fi

export PATH="/c/Program Files (x86)/DevDesktop/$PHP_ID:$PATH"

## set global composer folder to devdesktop
## removed since we admin rights - use deault user profile instead
## export COMPOSER_HOME="/c/Program Files (x86)/DevDesktop/tools"

if !(type "php.exe" &> /dev/null); then
  echo php.exe was not found.
  echo Available folder names are: \(export PHP_ID=foldername\)
  # Start with d is a folder
  # Match php_NUM_NUM
  ls "$(cd "$MY_SCRIPT_DIR" && cd .. && pwd)" -l | grep ^d | grep php[0-9]_[0-9]
  # Exit with error code 1
  exit 1
else
  php.exe "$MY_SCRIPT_DIR/composer.phar" ${@}
fi
